if(EXISTS "/home/runner/work/scaling-couscous/scaling-couscous/_codeql_build_dir/test_pressure[1]_tests.cmake")
  include("/home/runner/work/scaling-couscous/scaling-couscous/_codeql_build_dir/test_pressure[1]_tests.cmake")
else()
  add_test(test_pressure_NOT_BUILT test_pressure_NOT_BUILT)
endif()
